### ISSUE TITLE
add 4x4 grid

### ISSUE THREAD

**Issue by Subroutine7901** [Coding-Cactus/slidey#1]
hello, i would like a 4x4 version made, as the main version of this puzzle is 4x4, it may take time but should be quick, thank you!

**Comment by Coding-Cactus** [comment]
Good idea, I'll add it to the todo list

**Comment by Subroutine7901** [comment]
yay

**Comment by Coding-Cactus** [comment]
done it! https://github.com/Coding-Cactus/slidey/commit/a744b26e98160a72b363044fa89e9ae4152b236a

Thank you for your suggestion.
